from __future__ import annotations

DEFAULT_LANGUAGE = "ja"
LANGUAGE_NAMES = {
    "ja": "日本語",
    "en": "English",
}

TRANSLATIONS = {
    "ja": {
        "window_title": "MarkItDown GUI",
        "intro_text": "ローカルの PDF、DOCX、XLSX、HTML ファイルを Markdown に変換します。ファイルを追加し、出力フォルダを選んで、一括変換を実行してください。",
        "menu_settings": "設定",
        "action_copilot_setup": "GitHub Copilot CLI セットアップ",
        "language_label": "表示言語",
        "input_group": "入力ファイル",
        "button_add_files": "ファイル追加",
        "button_remove_selected": "選択行を削除",
        "button_clear_list": "一覧をクリア",
        "header_source": "元ファイル",
        "header_type": "種別",
        "header_status": "状態",
        "header_output": "出力先",
        "output_group": "出力",
        "output_folder_label": "出力フォルダ",
        "button_browse": "参照",
        "checkbox_overwrite": "同名の Markdown ファイルを上書きする",
        "checkbox_keep_data_uris": "HTML 出力で data URI を保持する",
        "checkbox_open_output": "完了後に出力フォルダを開く",
        "checkbox_copilot_format": "GitHub Copilot CLI で Markdown を整形する",
        "copilot_command_label": "Copilot CLI",
        "copilot_command_placeholder": "未入力時は自動検出します",
        "button_convert": "変換開始",
        "button_cancel": "キャンセル",
        "tab_preview": "プレビュー",
        "tab_log": "ログ",
        "dialog_select_files": "ファイルを選択",
        "dialog_file_filter": "対応ファイル (*.pdf *.docx *.xlsx *.html *.htm);;PDF (*.pdf);;Word (*.docx);;Excel (*.xlsx);;HTML (*.html *.htm)",
        "dialog_select_output": "出力フォルダを選択",
        "dialog_select_copilot_command": "Copilot CLI コマンドを選択",
        "dialog_copilot_command_filter": "コマンド (*.exe *.bat *.cmd *.ps1);;すべてのファイル (*)",
        "copilot_setup_dialog_title": "GitHub Copilot CLI セットアップ",
        "copilot_setup_intro": "この画面から GitHub Copilot CLI の実行パス確認、インストール案内の表示、CLI 起動による /login の実行導線をまとめて扱えます。",
        "copilot_setup_settings_group": "CLI 設定",
        "copilot_setup_button_auto_detect": "自動検出",
        "copilot_setup_button_check": "確認",
        "copilot_setup_button_launch": "CLI を開く",
        "copilot_setup_button_open_docs": "インストール案内を開く",
        "copilot_setup_status_label": "確認結果",
        "copilot_setup_status_not_checked": "まだ確認していません。",
        "copilot_setup_status_detected": "自動検出: {path}",
        "copilot_setup_status_ready": "CLI を確認できました: {detail}",
        "copilot_setup_status_ready_no_detail": "CLI を確認できました。",
        "copilot_setup_status_missing": "GitHub Copilot CLI が見つかりません。インストール後に自動検出または参照で設定してください。",
        "copilot_setup_status_timeout": "CLI の確認がタイムアウトしました。",
        "copilot_setup_status_error": "CLI の確認に失敗しました: {detail}",
        "copilot_setup_status_error_no_detail": "CLI の確認に失敗しました。",
        "copilot_setup_steps_group": "ガイド",
        "copilot_setup_steps_label": "推奨手順",
        "copilot_setup_steps_text": "1. 未インストールなら「インストール案内を開く」から GitHub Copilot CLI をインストールします。\n2. 「自動検出」または「参照」で copilot 実行ファイルを設定します。\n3. 「確認」で CLI が起動できるかを確認します。\n4. 「CLI を開く」で新しい PowerShell を開き、/login を実行して認証を完了します。\n5. このダイアログで Markdown 整形を有効にして保存します。",
        "copilot_setup_launch_title": "GitHub Copilot CLI",
        "copilot_setup_launch_message": "新しい PowerShell で GitHub Copilot CLI を開きました。必要ならその画面で /login を実行してください。",
        "copilot_setup_launch_failed": "GitHub Copilot CLI を起動できませんでした。",
        "log_close_requested": "変換中にウィンドウを閉じようとしたため、先にバッチをキャンセルします。",
        "log_skipped_duplicate": "重複ファイルをスキップしました: {path}",
        "log_skipped_path": "{path} をスキップしました: {reason}",
        "status_ready": "待機中",
        "status_processing": "変換中",
        "status_done": "完了",
        "status_failed": "失敗",
        "status_processing_detail_short": "{stage} {percent}%",
        "log_added_count": "{count} 件のファイルをバッチに追加しました。",
        "log_skipped_count": "{count} 件のファイルをスキップしました。詳細はログを確認してください。",
        "log_cleared": "バッチ一覧をクリアしました。",
        "default_output_folder_name": "MarkItDown 出力",
        "warning_output_folder_required_title": "出力フォルダが必要です",
        "warning_output_folder_required_message": "変換を開始する前に出力フォルダを選択してください。",
        "log_start_conversion": "{count} 件のファイルの変換を開始します。",
        "log_cancel_requested": "キャンセルを要求しました。",
        "log_cancellation_wait": "キャンセルを受け付けました。現在のファイルの処理完了を待っています。",
        "status_processing_path": "変換中: {path}",
        "log_converted": "変換完了: {source} -> {output}",
        "log_failed": "変換失敗: {source}: {message}",
        "status_progress": "{current} / {total} 件を処理しました。",
        "status_progress_detail": "変換中 {percent}% | {current}/{total} 件 | {stage}: {name}",
        "progress_stage_starting": "開始準備中",
        "progress_stage_validating": "入力を確認中",
        "progress_stage_xlsx_pdf": "Excel から PDF を生成中",
        "progress_stage_markitdown": "Markdown に変換中",
        "progress_stage_copilot": "GitHub Copilot CLI で整形中",
        "progress_stage_writing": "Markdown を保存中",
        "progress_stage_finalizing": "完了処理中",
        "progress_stage_failed": "エラー処理中",
        "log_batch_cancelled": "キャンセル要求によりバッチを終了しました。",
        "log_batch_finished": "バッチが完了しました。",
        "log_summary": "結果: 成功 {succeeded} 件、失敗 {failed} 件",
        "status_bar_summary": "ファイル数: {total} | 待機中: {ready} | 変換中: {processing} | 完了: {done} | 失敗: {failed}",
        "preview_select_row": "行を選択すると、生成された Markdown または最新のエラーを表示します。",
        "preview_failed_prefix": "変換に失敗しました。",
        "preview_no_output": "選択したファイルの出力はまだ生成されていません。",
        "log_language_changed": "表示言語を {language} に切り替えました。",
        "log_copilot_settings_updated": "GitHub Copilot CLI の設定を更新しました。",
        "validation_file_missing": "ファイルが存在しません。",
        "validation_folder_not_supported": "フォルダは対象外です。",
        "validation_unsupported_type": "非対応のファイル形式です: {suffix}",
        "runtime_markitdown_missing": "MarkItDown がインストールされていません。GUI を実行する前に markitdown[pdf,docx,xlsx] をインストールしてください。",
        "runtime_optional_dependency_missing": "必要なオプション依存が不足しています。markitdown[pdf,docx,xlsx] をインストールしてください。",
        "runtime_dependency_import_failed": "実行時依存の import に失敗しました。このパッケージと markitdown[pdf,docx,xlsx] を再インストールしてください。",
        "runtime_xlsx_pdf_powershell_missing": "PowerShell が見つかりません。XLSX を PDF 化するには Windows PowerShell が必要です。",
        "runtime_xlsx_pdf_excel_missing": "XLSX を PDF 化するための Microsoft Excel が見つかりません。Excel をインストールしてから .xlsx を変換してください。",
        "runtime_xlsx_pdf_output_missing": "Excel が想定した PDF 出力を生成しませんでした。",
        "runtime_xlsx_pdf_timeout": "XLSX の PDF 変換がタイムアウトしました。",
        "runtime_xlsx_pdf_failed": "XLSX の PDF 変換に失敗しました。",
        "runtime_unexpected_result": "MarkItDown が想定外の結果オブジェクトを返しました。",
        "runtime_copilot_missing": "GitHub Copilot CLI が見つかりません。CLI をインストールするか、GUI で実行パスを設定してください。",
        "runtime_copilot_auth": "GitHub Copilot CLI が認証されていません。CLI を一度開いて /login を完了するか、有効なトークンを設定してください。",
        "runtime_copilot_empty_output": "GitHub Copilot CLI が整形済み Markdown を返しませんでした。",
        "runtime_copilot_timeout": "GitHub Copilot CLI が制限時間内に整形結果を返しませんでした。",
        "runtime_copilot_failed": "GitHub Copilot CLI の実行に失敗しました。",
    },
    "en": {
        "window_title": "MarkItDown GUI",
        "intro_text": "Convert local PDF, DOCX, XLSX, and HTML files to Markdown. Add files, choose an output folder, and run a batch conversion.",
        "menu_settings": "Settings",
        "action_copilot_setup": "GitHub Copilot CLI Setup",
        "language_label": "Display Language",
        "input_group": "Input Files",
        "button_add_files": "Add Files",
        "button_remove_selected": "Remove Selected",
        "button_clear_list": "Clear List",
        "header_source": "Source File",
        "header_type": "Type",
        "header_status": "Status",
        "header_output": "Output",
        "output_group": "Output",
        "output_folder_label": "Output Folder",
        "button_browse": "Browse",
        "checkbox_overwrite": "Overwrite same-name Markdown files",
        "checkbox_keep_data_uris": "Keep data URIs in HTML output",
        "checkbox_open_output": "Open output folder when finished",
        "checkbox_copilot_format": "Shape Markdown with GitHub Copilot CLI",
        "copilot_command_label": "Copilot CLI",
        "copilot_command_placeholder": "Auto-detect when empty",
        "button_convert": "Convert",
        "button_cancel": "Cancel",
        "tab_preview": "Preview",
        "tab_log": "Log",
        "dialog_select_files": "Select Files",
        "dialog_file_filter": "Supported Files (*.pdf *.docx *.xlsx *.html *.htm);;PDF (*.pdf);;Word (*.docx);;Excel (*.xlsx);;HTML (*.html *.htm)",
        "dialog_select_output": "Select Output Folder",
        "dialog_select_copilot_command": "Select Copilot CLI Command",
        "dialog_copilot_command_filter": "Commands (*.exe *.bat *.cmd *.ps1);;All Files (*)",
        "copilot_setup_dialog_title": "GitHub Copilot CLI Setup",
        "copilot_setup_intro": "Use this dialog to verify the GitHub Copilot CLI path, open the installation guide, and launch a CLI window for the /login flow.",
        "copilot_setup_settings_group": "CLI Settings",
        "copilot_setup_button_auto_detect": "Auto Detect",
        "copilot_setup_button_check": "Check",
        "copilot_setup_button_launch": "Open CLI",
        "copilot_setup_button_open_docs": "Open Install Guide",
        "copilot_setup_status_label": "Status",
        "copilot_setup_status_not_checked": "Not checked yet.",
        "copilot_setup_status_detected": "Detected: {path}",
        "copilot_setup_status_ready": "CLI is available: {detail}",
        "copilot_setup_status_ready_no_detail": "CLI is available.",
        "copilot_setup_status_missing": "GitHub Copilot CLI was not found. Install it first, then use auto-detect or browse to configure it.",
        "copilot_setup_status_timeout": "CLI verification timed out.",
        "copilot_setup_status_error": "CLI verification failed: {detail}",
        "copilot_setup_status_error_no_detail": "CLI verification failed.",
        "copilot_setup_steps_group": "Guide",
        "copilot_setup_steps_label": "Recommended Steps",
        "copilot_setup_steps_text": "1. If the CLI is not installed yet, use Open Install Guide to install GitHub Copilot CLI.\n2. Use Auto Detect or Browse to point the GUI at the copilot executable.\n3. Use Check to confirm that the CLI can be launched.\n4. Use Open CLI to open a new PowerShell window, then run /login there to finish authentication.\n5. Enable Markdown shaping in this dialog and save the settings.",
        "copilot_setup_launch_title": "GitHub Copilot CLI",
        "copilot_setup_launch_message": "Opened GitHub Copilot CLI in a new PowerShell window. Run /login there if authentication is still required.",
        "copilot_setup_launch_failed": "GitHub Copilot CLI could not be launched.",
        "log_close_requested": "Close requested while conversion is still running. Cancelling the batch first.",
        "log_skipped_duplicate": "Skipped duplicate file: {path}",
        "log_skipped_path": "Skipped {path}: {reason}",
        "status_ready": "Ready",
        "status_processing": "Processing",
        "status_done": "Done",
        "status_failed": "Failed",
        "status_processing_detail_short": "{stage} {percent}%",
        "log_added_count": "Added {count} file(s) to the batch.",
        "log_skipped_count": "Skipped {count} file(s). Check the log for details.",
        "log_cleared": "Cleared the batch list.",
        "default_output_folder_name": "MarkItDown Output",
        "warning_output_folder_required_title": "Output Folder Required",
        "warning_output_folder_required_message": "Choose an output folder before starting the conversion.",
        "log_start_conversion": "Starting conversion for {count} file(s).",
        "log_cancel_requested": "Cancellation requested.",
        "log_cancellation_wait": "Cancellation requested. Waiting for the current file to finish.",
        "status_processing_path": "Processing: {path}",
        "log_converted": "Converted {source} -> {output}",
        "log_failed": "Failed {source}: {message}",
        "status_progress": "Processed {current} of {total} file(s).",
        "status_progress_detail": "Processing {percent}% | {current}/{total} file(s) | {stage}: {name}",
        "progress_stage_starting": "Preparing",
        "progress_stage_validating": "Validating input",
        "progress_stage_xlsx_pdf": "Exporting Excel to PDF",
        "progress_stage_markitdown": "Converting to Markdown",
        "progress_stage_copilot": "Shaping with GitHub Copilot CLI",
        "progress_stage_writing": "Writing Markdown output",
        "progress_stage_finalizing": "Finalizing",
        "progress_stage_failed": "Handling failure",
        "log_batch_cancelled": "Batch ended after cancellation.",
        "log_batch_finished": "Batch finished.",
        "log_summary": "Summary: {succeeded} succeeded, {failed} failed.",
        "status_bar_summary": "Files: {total} | Ready: {ready} | Processing: {processing} | Done: {done} | Failed: {failed}",
        "preview_select_row": "Select a row to inspect the generated Markdown or the latest error.",
        "preview_failed_prefix": "Conversion failed.",
        "preview_no_output": "No output has been generated for the selected file yet.",
        "log_language_changed": "Switched display language to {language}.",
        "log_copilot_settings_updated": "Updated the GitHub Copilot CLI settings.",
        "validation_file_missing": "File does not exist.",
        "validation_folder_not_supported": "Folders are not supported.",
        "validation_unsupported_type": "Unsupported file type: {suffix}",
        "runtime_markitdown_missing": "MarkItDown is not installed. Install markitdown[pdf,docx,xlsx] before running the GUI.",
        "runtime_optional_dependency_missing": "A required optional dependency is missing. Install markitdown[pdf,docx,xlsx].",
        "runtime_dependency_import_failed": "A runtime dependency could not be imported. Reinstall this package and markitdown[pdf,docx,xlsx].",
        "runtime_xlsx_pdf_powershell_missing": "PowerShell is not available. XLSX to PDF conversion requires Windows PowerShell.",
        "runtime_xlsx_pdf_excel_missing": "Microsoft Excel is not available for XLSX to PDF conversion. Install Excel on Windows before converting .xlsx files.",
        "runtime_xlsx_pdf_output_missing": "Excel did not generate the expected PDF output.",
        "runtime_xlsx_pdf_timeout": "XLSX to PDF conversion timed out.",
        "runtime_xlsx_pdf_failed": "XLSX to PDF conversion failed.",
        "runtime_unexpected_result": "MarkItDown returned an unexpected result object.",
        "runtime_copilot_missing": "GitHub Copilot CLI was not found. Install the CLI or configure its executable path in the GUI.",
        "runtime_copilot_auth": "GitHub Copilot CLI is not authenticated. Open the CLI once and complete /login, or configure a valid token.",
        "runtime_copilot_empty_output": "GitHub Copilot CLI returned no formatted Markdown.",
        "runtime_copilot_timeout": "GitHub Copilot CLI timed out before returning formatted Markdown.",
        "runtime_copilot_failed": "GitHub Copilot CLI failed.",
    },
}


def get_text(locale: str, key: str, **kwargs: object) -> str:
    selected_language = locale if locale in TRANSLATIONS else DEFAULT_LANGUAGE
    template = TRANSLATIONS[selected_language].get(
        key,
        TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key),
    )
    return template.format(**kwargs)